// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schedule.Context;

#nullable disable

namespace Schedule.Migrations
{
    [DbContext(typeof(ScheduleContext))]
    partial class ScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("C_has_S", b =>
                {
                    b.Property<int>("Cid")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("Cid", "Sid");

                    b.HasIndex("Sid");

                    b.ToTable("ClassSubjects");
                });

            modelBuilder.Entity("Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("T_has_C", b =>
                {
                    b.Property<int>("Tid")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Cid")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("Tid", "Cid");

                    b.HasIndex("Cid");

                    b.ToTable("TeacherClasses");
                });

            modelBuilder.Entity("T_has_S", b =>
                {
                    b.Property<int>("Tid")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("Tid", "Sid");

                    b.HasIndex("Sid");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Unterricht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Hour")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sid");

                    b.HasIndex("Cid", "Sid");

                    b.HasIndex("Tid", "Sid");

                    b.ToTable("Unterricht");
                });

            modelBuilder.Entity("C_has_S", b =>
                {
                    b.HasOne("Class", "Class")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subject", "Subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("T_has_C", b =>
                {
                    b.HasOne("Class", "Class")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teacher", "Teacher")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("T_has_S", b =>
                {
                    b.HasOne("Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Unterricht", b =>
                {
                    b.HasOne("Class", "Class")
                        .WithMany()
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("C_has_S", null)
                        .WithMany()
                        .HasForeignKey("Cid", "Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("T_has_S", null)
                        .WithMany()
                        .HasForeignKey("Tid", "Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Class", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("TeacherClasses");
                });

            modelBuilder.Entity("Subject", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.Navigation("TeacherClasses");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
