// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vererbung;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vererbung.Animals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Animals", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Vererbung.Bird", b =>
                {
                    b.HasBaseType("Vererbung.Animals");

                    b.Property<string>("Wingspan")
                        .HasColumnType("longtext");

                    b.ToTable("Birds", (string)null);
                });

            modelBuilder.Entity("Vererbung.Dog", b =>
                {
                    b.HasBaseType("Vererbung.Animals");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.ToTable("Dogs", (string)null);
                });

            modelBuilder.Entity("Vererbung.Bird", b =>
                {
                    b.HasOne("Vererbung.Animals", null)
                        .WithOne()
                        .HasForeignKey("Vererbung.Bird", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vererbung.Dog", b =>
                {
                    b.HasOne("Vererbung.Animals", null)
                        .WithOne()
                        .HasForeignKey("Vererbung.Dog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
